// Subject prompts for each category. The image generator uses these in three ways:
//
//  1. STYLE prompt + N candidates → user picks the best, renames to _anchor.png.
//     Defines background, lighting, framing, art style — locked in for the whole set.
//
//  2. COVER prompt → one image per category for the picker UI. Should represent
//     the topic but NOT appear in the playable card set.
//
//  3. SUBJECT prompts → 18 cards per category, each generated by feeding _anchor.png
//     back into Gemini with "swap the subject to X" so style/background stay identical.
//
// The label is what shows in game logs and is exposed to the client (alt text, etc.).

import type { CategoryId } from 'memory-game-shared';

export interface SubjectPrompt {
  imageId: string;
  label: string;
  subject: string;
}

export interface CategoryDef {
  id: CategoryId;
  // Style anchor: art direction + background. Used to generate _candidate-N.png.
  stylePrompt: string;
  // Cover image for the picker UI — represents the category, not in the card pool.
  coverPrompt: string;
  coverLabel: string;
  // 18 playable card subjects.
  subjects: SubjectPrompt[];
}

const STYLE_BASE =
  'Square 1:1 illustration. Subject perfectly centered with generous margin. ' +
  'High-quality painted storybook style, soft volumetric lighting, gentle rim light. ' +
  'No text, no logos, no borders, no watermarks. Single subject only.';

export const CATEGORIES_DATA: CategoryDef[] = [
  // ─── MAGICAL ───────────────────────────────────────────────────────────
  {
    id: 'magical',
    stylePrompt:
      `${STYLE_BASE} Background: a soft twilight purple sky with floating golden sparkles ` +
      `and a faint silhouette of a fairytale castle on the horizon. Warm golden rim light. ` +
      `Subject for this reference: a fairytale princess in a flowing blue gown with hands clasped.`,
    coverPrompt:
      `${STYLE_BASE} Background: a soft twilight purple sky with floating golden sparkles ` +
      `and a faint silhouette of a fairytale castle on the horizon. Warm golden rim light. ` +
      `Subject: an open enchanted storybook glowing with magical light, pages fluttering.`,
    coverLabel: 'enchanted storybook',
    subjects: [
      { imageId: 'card-001', label: 'princess', subject: 'a fairytale princess in a flowing blue gown with hands clasped' },
      { imageId: 'card-002', label: 'prince', subject: 'a brave prince holding a silver sword aloft' },
      { imageId: 'card-003', label: 'fairy godmother', subject: 'a kind fairy godmother holding a crescent moon wand' },
      { imageId: 'card-004', label: 'glass slipper', subject: 'a single glass slipper resting on a red velvet pillow' },
      { imageId: 'card-005', label: 'magic wand', subject: 'a slender magic wand with a glowing five-point star tip' },
      { imageId: 'card-006', label: 'talking teapot', subject: 'a smiling porcelain teapot with painted eyes and a bowtie' },
      { imageId: 'card-007', label: 'pumpkin carriage', subject: 'a golden pumpkin-shaped carriage with curly wheels' },
      { imageId: 'card-008', label: 'enchanted rose', subject: 'a single red rose floating inside a tall glass dome' },
      { imageId: 'card-009', label: 'castle', subject: 'a tall white fairytale castle with blue spires on a hilltop' },
      { imageId: 'card-010', label: 'magic mirror', subject: 'an ornate gilded magic mirror with a softly glowing surface' },
      { imageId: 'card-011', label: 'spinning wheel', subject: 'a wooden spinning wheel with shimmering golden thread' },
      { imageId: 'card-012', label: 'crown', subject: 'a jeweled royal crown resting on a velvet cushion' },
      { imageId: 'card-013', label: 'paper lantern', subject: 'a single floating paper lantern glowing warmly' },
      { imageId: 'card-014', label: 'royal horse', subject: 'a noble white horse wearing royal blue and gold armor' },
      { imageId: 'card-015', label: 'wishing well', subject: 'a stone wishing well with a small wooden roof and bucket' },
      { imageId: 'card-016', label: 'golden harp', subject: 'an elegant golden harp with carved swan-shaped pillars' },
      { imageId: 'card-017', label: 'genie lamp', subject: 'a brass genie lamp with curling wisps of blue smoke' },
      { imageId: 'card-018', label: 'pixie dust jar', subject: 'a glass jar full of glowing yellow pixie dust' },
    ],
  },

  // ─── MYSTICAL ──────────────────────────────────────────────────────────
  {
    id: 'mystical',
    stylePrompt:
      `${STYLE_BASE} Background: a misty twilight forest clearing with bioluminescent particles, ` +
      `a faint full moon overhead, mossy rocks framing the lower edges. Cool blue and teal light ` +
      `with a touch of warm magic. Subject for this reference: a noble white unicorn standing proud with a flowing mane.`,
    coverPrompt:
      `${STYLE_BASE} Background: a misty twilight forest clearing with bioluminescent particles, ` +
      `a faint full moon overhead, mossy rocks framing the lower edges. Cool blue and teal light. ` +
      `Subject: a glowing crystal orb floating above an open palm, radiating soft light.`,
    coverLabel: 'mystical crystal',
    subjects: [
      { imageId: 'card-001', label: 'unicorn', subject: 'a noble white unicorn with a flowing rainbow mane' },
      { imageId: 'card-002', label: 'red dragon', subject: 'a fierce red dragon with golden outstretched wings' },
      { imageId: 'card-003', label: 'griffin', subject: 'a tall griffin with eagle head and lion body' },
      { imageId: 'card-004', label: 'phoenix', subject: 'a phoenix bursting upward in orange and yellow flames' },
      { imageId: 'card-005', label: 'pegasus', subject: 'a white pegasus mid-gallop with feathered wings spread' },
      { imageId: 'card-006', label: 'basilisk', subject: 'a coiled green basilisk with shimmering scales' },
      { imageId: 'card-007', label: 'minotaur', subject: 'a horned minotaur holding a heavy stone hammer' },
      { imageId: 'card-008', label: 'centaur', subject: 'a centaur drawing back a longbow with one arrow' },
      { imageId: 'card-009', label: 'cerberus', subject: 'a three-headed black cerberus dog with red eyes' },
      { imageId: 'card-010', label: 'nine-tail fox', subject: 'a snow-white kitsune fox with nine flowing tails' },
      { imageId: 'card-011', label: 'kraken', subject: 'a single massive purple kraken tentacle rising up' },
      { imageId: 'card-012', label: 'jackalope', subject: 'a small brown jackalope rabbit with tall antlers' },
      { imageId: 'card-013', label: 'stone gargoyle', subject: 'a winged stone gargoyle perched on a pedestal' },
      { imageId: 'card-014', label: 'hippogriff', subject: 'a silver hippogriff with feathered front and horse rear' },
      { imageId: 'card-015', label: 'chimera', subject: 'a sleeping golden chimera with a snake tail' },
      { imageId: 'card-016', label: 'frost wyvern', subject: 'an icy blue frost wyvern with crystalline wings' },
      { imageId: 'card-017', label: 'wood nymph', subject: 'a small emerald wood nymph wreathed in leaves' },
      { imageId: 'card-018', label: 'thunderbird', subject: 'a great thunderbird with crackling lightning between its wings' },
    ],
  },

  // ─── TROPICAL ──────────────────────────────────────────────────────────
  {
    id: 'tropical',
    stylePrompt:
      `${STYLE_BASE} Background: pale turquoise water meeting warm white sand, ` +
      `soft palm leaf shadows across the foreground, golden sun glow from the upper right corner, ` +
      `a faint horizon line. Bright cheerful colors. Subject for this reference: a colorful striped beach hammock strung between two palm trunks.`,
    coverPrompt:
      `${STYLE_BASE} CRITICAL: Background must fill the ENTIRE square edge to edge — ` +
      `no white margins, no padding, no border. Background: deep turquoise ocean water with ` +
      `soft ripples, a low horizon, palm leaf shadows in the foreground, golden sun glow. ` +
      `Subject: a tiny tropical island with two palm trees rising from a sandbar in the center.`,
    coverLabel: 'tropical island',
    subjects: [
      { imageId: 'card-001', label: 'coconut drink', subject: 'a fresh coconut with a red striped straw and tiny umbrella' },
      { imageId: 'card-002', label: 'hibiscus', subject: 'a single bright red hibiscus flower in full bloom' },
      { imageId: 'card-003', label: 'surfboard', subject: 'a yellow longboard surfboard standing upright in the sand' },
      { imageId: 'card-004', label: 'cool pineapple', subject: 'a cheerful pineapple wearing round black sunglasses' },
      { imageId: 'card-005', label: 'tiki mask', subject: 'a carved wooden tiki mask with a red hibiscus flower' },
      { imageId: 'card-006', label: 'palm tree', subject: 'a single tall curved palm tree with a cluster of coconuts' },
      { imageId: 'card-007', label: 'flip flops', subject: 'a pair of blue flip flops resting in the sand' },
      { imageId: 'card-008', label: 'starfish', subject: 'a bright orange starfish next to a spiral seashell' },
      { imageId: 'card-009', label: 'parrot', subject: 'a colorful red and blue parrot perched on a branch' },
      { imageId: 'card-010', label: 'sun hat', subject: 'a wide straw sun hat with a long pink ribbon' },
      { imageId: 'card-011', label: 'sandcastle', subject: 'a tall sandcastle with three towers and a tiny flag' },
      { imageId: 'card-012', label: 'ukulele', subject: 'a small wooden ukulele with four strings' },
      { imageId: 'card-013', label: 'mango', subject: 'a juicy mango cut in half showing golden flesh' },
      { imageId: 'card-014', label: 'beach umbrella', subject: 'a striped red and white beach umbrella planted in sand' },
      { imageId: 'card-015', label: 'message bottle', subject: 'a corked glass bottle with a rolled paper message inside' },
      { imageId: 'card-016', label: 'flower lei', subject: 'a tropical lei made of pink and white orchids' },
      { imageId: 'card-017', label: 'shoreline chest', subject: 'an old wooden treasure chest open on the shoreline' },
      { imageId: 'card-018', label: 'crab', subject: 'a bright red crab holding a tiny seashell with one claw' },
    ],
  },

  // ─── JUNGLE ────────────────────────────────────────────────────────────
  {
    id: 'jungle',
    stylePrompt:
      `${STYLE_BASE} Background: a lush green jungle canopy with shafts of golden sunlight ` +
      `breaking through, broad tropical leaves framing the edges, soft mist in the distance. ` +
      `Rich saturated greens. Subject for this reference: a curious orange tiger peeking through wide jungle leaves.`,
    coverPrompt:
      `${STYLE_BASE} CRITICAL: Background must fill the ENTIRE square edge to edge — ` +
      `no white margins, no padding, no border. Background: dense green jungle canopy ` +
      `pushing all the way to every edge, broad tropical leaves dominating the corners, ` +
      `shafts of golden sunlight in the center, soft mist in the distance. ` +
      `Subject: a hanging vine carrying a yellow bunch of bananas in the center.`,
    coverLabel: 'jungle vine',
    subjects: [
      { imageId: 'card-001', label: 'tiger', subject: 'a curious orange tiger with bright green eyes peeking through leaves' },
      { imageId: 'card-002', label: 'gorilla', subject: 'a strong silverback gorilla sitting calmly' },
      { imageId: 'card-003', label: 'leopard', subject: 'a spotted leopard lounging on a thick tree branch' },
      { imageId: 'card-004', label: 'macaw', subject: 'a brilliant red and blue macaw parrot mid-flight' },
      { imageId: 'card-005', label: 'tree frog', subject: 'a tiny bright green tree frog with red eyes on a leaf' },
      { imageId: 'card-006', label: 'baby elephant', subject: 'a baby elephant with a raised curling trunk' },
      { imageId: 'card-007', label: 'sloth', subject: 'a smiling sloth hanging upside down from a branch' },
      { imageId: 'card-008', label: 'toucan', subject: 'a black toucan with a huge rainbow-colored beak' },
      { imageId: 'card-009', label: 'python', subject: 'a green python coiled neatly on a fallen log' },
      { imageId: 'card-010', label: 'monkey', subject: 'a brown capuchin monkey holding a yellow banana' },
      { imageId: 'card-011', label: 'chameleon', subject: 'a chameleon turning purple while gripping a twig' },
      { imageId: 'card-012', label: 'okapi', subject: 'a striped okapi half-hidden behind giant leaves' },
      { imageId: 'card-013', label: 'jaguar', subject: 'a black jaguar drinking from a small jungle stream' },
      { imageId: 'card-014', label: 'quetzal', subject: 'a brilliant green quetzal bird with very long tail feathers' },
      { imageId: 'card-015', label: 'tapir', subject: 'a chunky black and white tapir snuffling at the ground' },
      { imageId: 'card-016', label: 'fruit bat', subject: 'a brown fruit bat hanging upside down from a branch' },
      { imageId: 'card-017', label: 'anteater', subject: 'a giant anteater with its long curling snout extended' },
      { imageId: 'card-018', label: 'morpho butterfly', subject: 'a single iridescent blue morpho butterfly with open wings' },
    ],
  },

  // ─── DEEP SEA ──────────────────────────────────────────────────────────
  {
    id: 'deep-sea',
    stylePrompt:
      `${STYLE_BASE} Background: deep navy ocean depths with bioluminescent particles drifting, ` +
      `faint pale light rays descending from above, dark kelp silhouettes at the lower edges. ` +
      `Cool ethereal blues and teals with glowing accents. Subject for this reference: a glowing pink jellyfish drifting with trailing tentacles.`,
    coverPrompt:
      `${STYLE_BASE} Background: deep navy ocean depths with bioluminescent particles drifting, ` +
      `faint pale light rays descending from above, dark kelp silhouettes at the lower edges. ` +
      `Subject: an ancient sunken treasure chest covered in seaweed, glowing softly from within.`,
    coverLabel: 'sunken treasure',
    subjects: [
      { imageId: 'card-001', label: 'jellyfish', subject: 'a glowing pink jellyfish with long trailing tentacles' },
      { imageId: 'card-002', label: 'anglerfish', subject: 'a toothy anglerfish with a single glowing yellow lure' },
      { imageId: 'card-003', label: 'giant squid', subject: 'a giant squid with curling outstretched tentacles' },
      { imageId: 'card-004', label: 'orca', subject: 'a sleek black and white orca whale swimming forward' },
      { imageId: 'card-005', label: 'blue ringed octopus', subject: 'a small octopus covered in glowing blue rings' },
      { imageId: 'card-006', label: 'great white', subject: 'a great white shark cruising mouth-first' },
      { imageId: 'card-007', label: 'seahorse', subject: 'a yellow seahorse with a tightly curled tail' },
      { imageId: 'card-008', label: 'manta ray', subject: 'a large manta ray gliding with wings outstretched' },
      { imageId: 'card-009', label: 'lantern fish', subject: 'a small lantern fish with a glowing belly stripe' },
      { imageId: 'card-010', label: 'hermit crab', subject: 'a hermit crab tucked into a striped spiral shell' },
      { imageId: 'card-011', label: 'coral branch', subject: 'a pink coral branch with a small purple anemone' },
      { imageId: 'card-012', label: 'nautilus', subject: 'a nautilus with a brown striped spiral shell' },
      { imageId: 'card-013', label: 'swordfish', subject: 'a silver swordfish leaping with a long sharp bill' },
      { imageId: 'card-014', label: 'sardine school', subject: 'a tight school of silver sardines swirling together' },
      { imageId: 'card-015', label: 'ghost shrimp', subject: 'a translucent ghost shrimp with delicate antennae' },
      { imageId: 'card-016', label: 'sea urchin', subject: 'a deep red sea urchin with long spines' },
      { imageId: 'card-017', label: 'dumbo octopus', subject: 'a small purple dumbo octopus with ear-like fins' },
      { imageId: 'card-018', label: 'mermaid', subject: 'a mermaid with long flowing hair and a turquoise tail' },
    ],
  },
];

export function getCategory(id: CategoryId): CategoryDef {
  const cat = CATEGORIES_DATA.find((c) => c.id === id);
  if (!cat) throw new Error(`Unknown category: ${id}`);
  return cat;
}
