export const GRID_COLS = 5;
export const GRID_ROWS = 5;
export const GRID_CELLS = GRID_COLS * GRID_ROWS; // 25
export const CENTER_CELL = Math.floor(GRID_CELLS / 2); // position 12 (center of 5x5)
export const TOTAL_CARDS = GRID_CELLS - 1; // 24 (center is empty)
export const TOTAL_PAIRS = TOTAL_CARDS / 2; // 12
export const SUDDEN_DEATH_PAIRS = 2; // 4 cards, 2 fresh images for the tiebreaker
export const CARD_FLIP_DELAY_MS = 800;
export const MIN_IMAGE_POOL_SIZE = 20;
export const SERVER_PORT = 3001;
export const CLIENT_PORT = 5173;
